package com.sequenceiq.datalake.flow.dr;

import com.sequenceiq.flow.core.FlowEvent;

public enum DatalakeDatabaseDrEvent implements FlowEvent {

    DATALAKE_DATABASE_BACKUP_EVENT("DATALAKE_DATABASE_BACKUP_EVENT"),
    DATALAKE_DATABASE_BACKUP_COULD_NOT_START_EVENT("DATALAKE_DATABASE_BACKUP_COULD_NOT_START_EVENT"),
    DATALAKE_DATABASE_BACKUP_IN_PROGRESS_EVENT("DATALAKE_DATABASE_BACKUP_IN_PROGRESS_EVENT"),
    DATALAKE_DATABASE_BACKUP_SUCCESS_EVENT("DATALAKE_DATABASE_BACKUP_SUCCESS_EVENT"),
    DATALAKE_DATABASE_BACKUP_FAILED_EVENT("DATALAKE_DATABASE_BACKUP_FAILED_EVENT"),
    DATALAKE_DATABASE_BACKUP_FINALIZED_EVENT("DATALAKE_DATABASE_BACKUP_FINALIZED_EVENT"),
    DATALAKE_DATABASE_BACKUP_FAILURE_HANDLED_EVENT("DATALAKE_DATABASE_BACKUP_FAILURE_HANDLED_EVENT"),
    DATALAKE_DATABASE_RESTORE_EVENT("DATALAKE_DATABASE_RESTORE_EVENT"),
    DATALAKE_DATABASE_RESTORE_COULD_NOT_START_EVENT("DATALAKE_DATABASE_RESTORE_COULD_NOT_START_EVENT"),
    DATALAKE_DATABASE_RESTORE_IN_PROGRESS_EVENT("DATALAKE_DATABASE_RESTORE_IN_PROGRESS_EVENT"),
    DATALAKE_DATABASE_RESTORE_SUCCESS_EVENT("DATALAKE_DATABASE_RESTORE_SUCCESS_EVENT"),
    DATALAKE_DATABASE_RESTORE_FAILED_EVENT("DATALAKE_DATABASE_RESTORE_FAILED_EVENT"),
    DATALAKE_DATABASE_RESTORE_FINALIZED_EVENT("DATALAKE_DATABASE_RESTORE_FINALIZED_EVENT"),
    DATALAKE_DATABASE_RESTORE_FAILURE_HANDLED_EVENT("DATALAKE_DATABASE_RESTORE_FAILURE_HANDLED_EVENT");

    private final String event;

    DatalakeDatabaseDrEvent(String event) {
        this.event = event;
    }

    @Override
    public String event() {
        return event;
    }
}
